---
abstract: 'write message handling apps with Catalyst.'
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Engine-Stomp
no_index:
  directory:
    - inc
    - t
  package:
    - StompTestApp
requires:
  Catalyst::Action::REST: 0
  Catalyst::Engine::Embeddable: 0.0.1
  Catalyst::Runtime: 5.80003
  Moose: 0
  MooseX::Workers: 0.05
  Net::Stomp: 0.34
  YAML::XS: 0.32
  namespace::autoclean: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
